### ISSUE TITLE
Time Handling

### ISSUE THREAD

**Issue by josephhardinee** [josephhardinee/PyDSD#49]
I wanted to write this down since we've gone back and forth a bit (or at least I have).
I'm going to modify all the readers to have the following time field. Time will be stored as a series of integers representing seconds since 1970-1-1 (epoch time). So
time['data'] = array([  1.32332381e+09,   1.32332382e+09,   1.32332383e+09]) for instance. It will have a units string set as well. 
 'units': 'seconds since 1970-1-1 00:00:00+0:00'

Currently we have a mix of epoch time, time offset from beginning of file, and datetime instances. 
Does this work for you @nguy ? I will try to route much of our time handling through some common functions so that if we change our mind in the future, its an easier update than modifying each reader individually. I think this reflects what we discussed at AMS,

**Comment by josephhardinee** [comment]
I am concerned about the case where we don't know the basetime however and only have seconds since start of file. Do we just make up a basetime?

**Comment by nguy** [comment]
I think that is a valid concern. If we build the common architecture so that there is a value and a unit string, then either will work to be converted to a datetime instance. In reality it doesn't much matter as long as the tools all are coded to read the same information. In the case of when no basetime is provided, one option is that we could either 1. Make a guess and print out what that guess is or 2. Throw an error that user must provide basetime information.

**Comment by josephhardinee** [comment]
Okay I think we'll mandate that we do epoch time in int, that way if we change mind in future we can just overwrap all time handling to convert it to whatever. 

For no basetime, I don't like 2 as it puts a bigger load on user and can make automation hard. Perhaps we just set it to be epoch time 1, and issue a warning? Guessing might be problematic as I'm not sure how we'd handle that. 

I do think we can add a option to some of the readers that don't guarantee a known time to set a basetime?
