### ISSUE TITLE
End of Life for python 2.7

### ISSUE THREAD

**Issue by josephhardinee** [josephhardinee/PyDSD#71]
@nguy , I am thinking of announcing an end of life for python 2.7 at the end of the year (or earlier?). It mirrors the move by a lot of projects to cut support and it would make some maintenance tasks a fair bit easier. Thoughts?

**Comment by nguy** [comment]
I support this idea. I think the tide has turned enough to move on from python 2.

**Comment by scollis** [comment]
FYI I will be issuing the Python 3 edict for Py-ART very soon. Planned last
version supporting Py2.7 will be our fall release this year. Spring 2019
will see a Py3 only release


Scott Collis


On Jul 19, 2018 at 8:21 AM, Nick Guy <notifications@github.com> wrote:


I support this idea. I think the tide has turned enough to move on from
python 2.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/josephhardinee/PyDSD/issues/71#issuecomment-406273947>,
or mute the thread

**Comment by josephhardinee** [comment]
I think we can plan on something similar and do one last release as py27 supported, and then switch to only 3.5+. I'll draft a pull request up modifying the README to include this information.

**Comment by josephhardinee** [comment]
With the new year we will now consider Python 2.7 not supported.
